version: 0.2

env:
  variables:
    DOCKER_BUILDKIT: "1"

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - "apt update"
      - "apt install rpm -y"
      - "pip3 install boto3"
      - "wget https://github.com/aquasecurity/trivy/releases/download/v0.38.1/trivy_0.38.1_Linux-64bit.deb"
      - "dpkg -i trivy_0.38.1_Linux-64bit.deb"
      - trivy --version
  pre_build:
    commands:
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - docker build -t ${REPOSITORY_URI}:${IMAGE_TAG} .
  build:
    commands:
      #- trivy -f json -o results.json --exit-code 0 --severity HIGH,MEDIUM,LOW --quiet --auto-refresh ${REPOSITORY_URI}:${IMAGE_TAG}
      #- trivy -f json -o results.json --exit-code 1 --severity HIGH,CRITICAL --quiet --auto-refresh ${REPOSITORY_URI}:${IMAGE_TAG}
      - trivy image ${REPOSITORY_URI}:${IMAGE_TAG} -f json -o results.json --exit-code 1 --severity HIGH,CRITICAL --quiet
  post_build:
    commands:
      - echo trivy scan results S3 upload on `date`
      - cat results.json
artifacts:
  files:
    - imagedefinitions.json
    - results.json
